# Generated by Django 5.2.11 on 2026-03-05 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('visual_selection_ids', models.JSONField(blank=True, default=list)),
                ('product_types', models.JSONField(blank=True, default=list)),
                ('fabrics', models.JSONField(blank=True, default=list)),
                ('fabric_is_flexible', models.BooleanField(default=False)),
                ('fabric_not_sure', models.BooleanField(default=False)),
                ('craft_interest', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('exploring', "I'm exploring")], max_length=20, null=True)),
                ('crafts', models.JSONField(blank=True, default=list)),
                ('craft_is_flexible', models.BooleanField(default=False)),
                ('craft_not_sure', models.BooleanField(default=False)),
                ('experimentation', models.CharField(choices=[('yes', "Yes, I'd like to explore"), ('no', 'Not a priority right now'), ('skipped', 'Skipped')], default='skipped', max_length=20)),
                ('process_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('design_support', models.JSONField(blank=True, default=list)),
                ('timeline', models.CharField(blank=True, choices=[('1_3_months', '1-3 months'), ('3_6_months', '3-6 months'), ('6_plus_months', '6 months or longer'), ('not_sure', 'Not sure yet'), ('flexible', "I'm flexible")], max_length=20, null=True)),
                ('batch_size', models.CharField(blank=True, choices=[('under_30', 'Under 30 pieces'), ('30_100', '30-100 pieces'), ('over_100', '100+ pieces'), ('not_sure', 'Not sure yet')], max_length=20, null=True)),
                ('journey_stage', models.CharField(blank=True, choices=[('figuring_it_out', 'Figuring It Out'), ('build_with_support', 'Build With Support'), ('ready_to_produce', 'Ready to Produce')], max_length=30, null=True)),
                ('matching_complete', models.BooleanField(default=False)),
                ('zero_match_suggestions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'buyer_profiles',
            },
        ),
        migrations.CreateModel(
            name='StudioRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank_position', models.PositiveIntegerField()),
                ('ranking', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('core_capability_fit', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('moq_fit', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('craft_approach_fit', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('visual_affinity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('match_reasoning', models.JSONField(default=dict)),
                ('what_best_at', models.JSONField(default=list)),
                ('what_to_keep_in_mind', models.JSONField(default=list)),
                ('is_bonus_visual', models.BooleanField(default=False)),
                ('selected_image_ids', models.JSONField(default=list)),
                ('mismatches', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='discovery.buyerprofile')),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_recommendations', to='core.sellerprofile')),
            ],
            options={
                'db_table': 'studio_recommendations',
                'ordering': ['rank_position'],
            },
        ),
        migrations.AddIndex(
            model_name='buyerprofile',
            index=models.Index(fields=['session_token'], name='buyer_profi_session_23b888_idx'),
        ),
        migrations.AddIndex(
            model_name='buyerprofile',
            index=models.Index(fields=['user'], name='buyer_profi_user_id_f476cb_idx'),
        ),
        migrations.AddIndex(
            model_name='buyerprofile',
            index=models.Index(fields=['created_at'], name='buyer_profi_created_709dac_idx'),
        ),
        migrations.AddIndex(
            model_name='studiorecommendation',
            index=models.Index(fields=['buyer_profile', 'is_bonus_visual'], name='studio_reco_buyer_p_557f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='studiorecommendation',
            index=models.Index(fields=['seller_profile'], name='studio_reco_seller__dacab2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studiorecommendation',
            unique_together={('buyer_profile', 'seller_profile')},
        ),
    ]
