# Generated by Django 5.2.11 on 2026-03-10 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_inquiries', to='discovery.buyerprofile')),
            ],
            options={
                'db_table': 'custom_inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudioInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('answers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_inquiries', to='discovery.buyerprofile')),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_inquiries', to='core.sellerprofile')),
            ],
            options={
                'db_table': 'studio_inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller_profile'], name='studio_inqu_seller__26cb47_idx'), models.Index(fields=['email'], name='studio_inqu_email_4a528c_idx')],
            },
        ),
    ]
