# Generated by Django 5.2.11 on 2026-03-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiodetails',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
